### Get all regions
GET http://localhost:3000/regions HTTP/1.1
Accept: application/json

### Get single region
GET http://localhost:3000/regions/67c021ef35f76cb310d30c74 HTTP/1.1
Accept: application/json

### Get all user regions
GET http://localhost:3000/regions?user=67bfd99cfa80dcab259f6832 HTTP/1.1
Accept: application/json

### Get all regions near point (longitude, latitude, distance)
GET http://localhost:3000/regions/point-distance/-47.112952282523196/-18.40004856723054/15 HTTP/1.1
Accept: application/json

### Get all user regions near point (longitude, latitude, distance)
GET http://localhost:3000/regions/point-distance/-47.112952282523196/-18.40004856723054/15?user=67bfd99cfa80dcab259f6832 HTTP/1.1
Accept: application/json

### Get region which includes point (longitude, latitude)
GET http://localhost:3000/regions/includes-point/-46.955536502973075/-19.464130255663207 HTTP/1.1
Accept: application/json

### Get user region which includes point (longitude, latitude)
GET http://localhost:3000/regions/includes-point/-46.955536502973075/-19.464130255663207?user=67bfd99cfa80dcab259f6832 HTTP/1.1
Accept: application/json

### Create region
POST http://localhost:3000/regions HTTP/1.1
Content-Type: application/json

{
  "name": "Polígono A",
  "polygon": {
    "coordinates":[
              [
                [
                  -47.115052282523196,
                  -18.42004856723054
                ],
                [
                  -47.112952282523196,
                  -18.508521684870615
                ],
                [
                  -47.03607795454727,
                  -18.508521684870615
                ],
                [
                  -47.03607795454727,
                  -18.45004856723054
                ],
                [
                  -47.115052282523196,
                  -18.42004856723054
                ]
              ]
            ],
    "type": "Polygon"
  },
  "userId": "67bfd99cfa80dcab259f6832"
}

### Edit region name
PATCH  http://localhost:3000/regions/67bf7e7c522562b8db4971f4/name HTTP/1.1
Content-Type: application/json

{
  "name": "Polígono A (Próximo)"
}

### Delete region
DELETE http://localhost:3000/regions/67c021ef35f76cb310d30c74 HTTP/1.1
Accept: application/json

### Get users with pagination
GET http://localhost:3000/users?page=0&limit=10 HTTP/1.1
Accept: application/json

### Create user with coordinates
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "email": "user1@email.com",
  "name": "meu nome",
  "coordinates": [8.5398562, 47.3724404]
}

### Create user with address
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "email": "user2@email.com",
  "name": "meu nome",
  "address": "Alameda das Orquídeas - Granja Ouro Branco"
}
### Get user
GET http://localhost:3000/users/67c01f3897a70d9d7ff46a6f HTTP/1.1
Accept: application/json

### Update user address
PATCH http://localhost:3000/users/67c01f3897a70d9d7ff46a6f/address HTTP/1.1
Content-Type: application/json

{
  "address": "Rio de Janeiro, Rio de Janeiro"
}

### Delete user
DELETE http://localhost:3000/users/67c01f3897a70d9d7ff46a6f HTTP/1.1
Accept: application/json
